--US306--

/*INSERT INTO STAFF(STAFF_ID, NAME, CARGO_MANIFEST_ID, LOCATION_ID )
VALUES('463143', 'Freida Slimming', '23423', '980587');*/

SET SERVEROUTPUT ON;

DROP FUNCTION getOccupancyRate;
CREATE OR REPLACE FUNCTION getOccupancyRate(v_STAFF_ID STAFF.STAFF_ID%TYPE)
RETURN VARCHAR IS 

    v_306 INTEGER;
    v_occupancyRate INTEGER;
    v_containersLeaving INTEGER;

BEGIN

    SELECT ((SELECT COUNT(*)
        FROM CONTAINER c
        INNER JOIN CONTAINER_CARGO_MANIFEST ccm ON ccm.CONTAINER_ID = c.CONTAINER_ID 
        INNER JOIN CARGO_MANIFEST cm ON cm.CARGO_MANIFEST_ID = ccm.CARGO_MANIFEST_ID
        INNER JOIN STAFF s ON s.CARGO_MANIFEST_ID = cm.CARGO_MANIFEST_ID
        WHERE STAFF_ID = 463143) / l.CAPACITY) * 100 AS "OCCUPANCY RATE(%)" INTO v_occupancyRate
    FROM LOCATION l, STAFF s
    WHERE l.TYPE = 'warehouse'
    AND s.STAFF_ID = 463143;
            
    SELECT COUNT(*) AS "CONTAINERS LEAVING" INTO v_containersLeaving
    FROM TRIP t, LOCATION l, STAFF s 
    WHERE t.DEPARTURE = l.LOCATION_ID
    AND t.DEPARTURE_DATE > SYSDATE 
    AND t.DEPARTURE_DATE < SYSDATE + INTERVAL '31' DAY
    AND s.STAFF_ID = 463143;
        


    v_306 := 'OCCUPANCY RATE(%): ' || v_occupancyRate || 'CONTAINERS LEAVING: ' || v_containersLeaving;
    

RETURN (v_occupancyRate);

END;

BEGIN
DBMS_OUTPUT.PUT_LINE(getOccupancyRate(463143));
END;


/*UPDATE LOCATION
SET CAPACITY = 43
WHERE LOCATION_ID = 980587;*/

/*UPDATE LOCATION
SET COUNTRY = 'Spain'
WHERE LOCATION_ID = 980587;*/

/*UPDATE STAFF
SET LOCATION_ID = 980587
WHERE STAFF_ID = 463143*/
