
SET SERVEROUTPUT ON;

DROP FUNCTION fnc_get_Cargo_Per_Year;
CREATE OR REPLACE FUNCTION fnc_get_Cargo_Per_Year(p_YEAR INT)
return NUMBER

is
v_cargo_per_year INTEGER;
BEGIN


SELECT  (COUNT(CARGO_MANIFEST_ID)) INTO v_cargo_per_year
FROM CARGO_MANIFEST 
WHERE (EXTRACT(YEAR FROM MANIFEST_DATE ))=p_YEAR 
GROUP BY EXTRACT (YEAR FROM MANIFEST_DATE);

RETURN v_cargo_per_year;

END;

BEGIN 
DBMS_OUTPUT.PUT_LINE(fnc_get_Cargo_Per_Year(2019));
END;




SET SERVEROUTPUT ON;

DROP FUNCTION fnc_get_Containers_Avg;
CREATE OR REPLACE FUNCTION fnc_get_Containers_Avg(p_YEAR INT)
return NUMBER
is
v_avg_containers NUMBER;
BEGIN

SELECT (AVG( COUNT(a.CONTAINER_ID))) INTO v_avg_containers
FROM CONTAINER_CARGO_MANIFEST a
INNER JOIN CARGO_MANIFEST b  ON a.CARGO_MANIFEST_ID = b.CARGO_MANIFEST_ID
AND (EXTRACT(YEAR FROM MANIFEST_DATE ))=p_YEAR
GROUP BY a.CARGO_MANIFEST_ID;

RETURN v_avg_containers;
END;

BEGIN 
DBMS_OUTPUT.PUT_LINE(fnc_get_Containers_Avg(2020));
END;