CREATE OR REPLACE TRIGGER AUDIT_TRAIL
AFTER INSERT OR UPDATE OR DELETE
ON CONTAINER_CARGO_MANIFEST
BEGIN
IF: INSERTING 
THEN
INSERT INTO AUDIT_TRAIL (CONTAINER_ID,CARGO_MANIFEST_ID, USERNAME, TYPE_OPERATION, DATE_TIME_OPERATION)
VALUES (:NEW.CONTAINER_ID, :NEW.CARGO_MANIFEST_ID, USERNAME,'INSERT', SYSDATE);
END IF;

IF: UPDATING 
THEN
INSERT INTO AUDIT_TRAIL (CONTAINER_ID,CARGO_MANIFEST_ID, USERNAME, TYPE_OPERATION, DATE_TIME_OPERATION)
VALUES (:NEW.CONTAINER_ID, :NEW.CARGO_MANIFEST_ID, USERNAME,'UPDATE', SYSDATE);
END IF;

IF: DELETING 
THEN
INSERT INTO AUDIT_TRAIL (CONTAINER_ID,CARGO_MANIFEST_ID, USERNAME, TYPE_OPERATION, DATE_TIME_OPERATION)
VALUES (:OLD.CONTAINER_ID, :OLD.CARGO_MANIFEST_ID, USERNAME,'DELETE', SYSDATE);
END IF;

END;