--US407--

SET SERVEROUTPUT ON;

DROP FUNCTION generateMaps1;
CREATE OR REPLACE FUNCTION generateMaps1(v_STAFF_ID STAFF.STAFF_ID%TYPE)
RETURN VARCHAR IS
    v_COUNT INTEGER;
    v_MAP VARCHAR(1000);
    v_CONTAINERS VARCHAR(100);

BEGIN
FOR i IN(SELECT t.DEPARTURE_DATE, t.ARRIVAL_DATE, v.VEHICLE_ID, s.MMSI, cm.CARGO_MANIFEST_ID, cm.TYPE, l.NAME, c.CONTAINER_ID, ccm.X, ccm.Y, ccm.Z
    FROM VEHICLE v
        INNER JOIN SHIP s ON s.VEHICLE_ID = v.VEHICLE_ID
        INNER JOIN STAFF_SHIP sts ON sts.MMSI = s.MMSI
        INNER JOIN STAFF st ON st.STAFF_ID = sts.STAFF_ID
        INNER JOIN SHIP_CONTAINER sc ON sc.MMSI = s.MMSI
        INNER JOIN CONTAINER c ON c.CONTAINER_ID = sc.CONTAINER_ID
        INNER JOIN CONTAINER_CARGO_MANIFEST ccm ON ccm.CONTAINER_ID = c.CONTAINER_ID
        INNER JOIN CARGO_MANIFEST cm ON v.VEHICLE_ID = cm.VEHICLE_ID
        INNER JOIN STOPS ss ON cm.STOPS_NAME = ss.STOPS_NAME
        INNER JOIN TRIP t ON t.TRIP_ID = ss.TRIP_ID
        INNER JOIN LOCATION l ON l.TRIP_ID = t.TRIP_ID
    WHERE t.ARRIVAL_DATE < SYSDATE + INTERVAL '8' DAY
    AND t.DEPARTURE_DATE > SYSDATE
    AND st.STAFF_ID = v_STAFF_ID
    ORDER BY t.ARRIVAL_DATE)
    

LOOP
    SELECT COUNT(*) INTO v_COUNT
    FROM CONTAINER_CARGO_MANIFEST cm
    WHERE CARGO_MANIFEST_ID = cm.CARGO_MANIFEST_ID;
    
    v_MAP := 'NUMBER OF CONTAINERS: ' || v_COUNT || '   DEPARTURE DATE: ' ||i.DEPARTURE_DATE || '   ARRIVAL DATE: ' || i.ARRIVAL_DATE || '  VEHICLE ID: ' || i.VEHICLE_ID || '  SHIP MMSI: ' || i.MMSI || ' CARGO MANIFEST ID: ' || i.CARGO_MANIFEST_ID || '    TYPE OF MANIFEST: ' || i.TYPE || '  LOCATION: ' || i.NAME || '  CONTAINER ID: ' || i.CONTAINER_ID || '  X: ' || i.X || '    Y: ' || i.Y || '    Z: ' || i.Z;
    return (v_MAP);
END LOOP;

END;

BEGIN 
DBMS_OUTPUT.PUT_LINE(generateMaps1(9876));
END;