--US305--

/*UPDATE CARGO_MANIFEST
SET VEHICLE_ID = 17465
WHERE CARGO_MANIFEST_ID = 23423;*/

SET SERVEROUTPUT ON;

DROP FUNCTION routeOfContainer;
CREATE OR REPLACE FUNCTION routeOfContainer(v_CLIENT_ID CLIENT.CLIENT_ID%TYPE, v_CONTAINER_ID CONTAINER.CONTAINER_ID%TYPE)
RETURN VARCHAR IS
    v_ROUTE VARCHAR(200);
    v_DEPARTURE VARCHAR(100);
    v_ARRIVAL VARCHAR(100);
    v_DEPARTURE_DATE DATE;
    v_ARRIVAL_DATE DATE;
    v_VEHICLE_ID INTEGER;
    v_FINDCONTAINER INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO v_FINDCONTAINER
    FROM CARGO_MANIFEST cm
        INNER JOIN STOPS s ON s.STOPS_NAME = cm.STOPS_NAME
        INNER JOIN TRIP t ON t.TRIP_ID = s.TRIP_ID
        INNER JOIN CONTAINER_CARGO_MANIFEST ccm ON ccm.CARGO_MANIFEST_ID = cm.CARGO_MANIFEST_ID
        INNER JOIN CONTAINER cont ON cont.CONTAINER_ID = ccm.CONTAINER_ID
        INNER JOIN CLIENT_CONTAINER clcont ON clcont.CONTAINER_ID = cont.CONTAINER_ID
        INNER JOIN CLIENT cl ON cl.CLIENT_ID = clcont.CLIENT_ID
    WHERE cont.CONTAINER_ID = v_CONTAINER_ID AND cl.CLIENT_ID = v_CLIENT_ID AND cm.CARGO_MANIFEST_ID = ccm.CARGO_MANIFEST_ID;
    
--TRIGGER
    IF v_FINDCONTAINER < 1 THEN
        raise_application_error(-20999, 'The provided ID is not valid/leased by the client! Please insert again.');

    ELSE
        SELECT COUNT(*), cm.VEHICLE_ID, t.DEPARTURE, t.ARRIVAL, t.ARRIVAL_DATE, t.DEPARTURE_DATE
        INTO v_FINDCONTAINER, v_VEHICLE_ID, v_DEPARTURE, v_ARRIVAL, v_ARRIVAL_DATE, v_DEPARTURE_DATE 
        FROM CARGO_MANIFEST cm
            INNER JOIN STOPS s ON s.STOPS_NAME = cm.STOPS_NAME
            INNER JOIN TRIP t ON t.TRIP_ID = s.TRIP_ID
            INNER JOIN CONTAINER_CARGO_MANIFEST ccm ON ccm.CARGO_MANIFEST_ID = cm.CARGO_MANIFEST_ID
            INNER JOIN CONTAINER cont ON cont.CONTAINER_ID = ccm.CONTAINER_ID
            INNER JOIN CLIENT_CONTAINER clcont ON clcont.CONTAINER_ID = cont.CONTAINER_ID
            INNER JOIN CLIENT cl ON cl.CLIENT_ID = clcont.CLIENT_ID
        WHERE cont.CONTAINER_ID = v_CONTAINER_ID AND cl.CLIENT_ID = v_CLIENT_ID AND cm.CARGO_MANIFEST_ID = ccm.CARGO_MANIFEST_ID
        GROUP BY cm.VEHICLE_ID, t.DEPARTURE, t.ARRIVAL, t.ARRIVAL_DATE, t.DEPARTURE_DATE;
        
        v_ROUTE := 'VEHICLE_ID: ' || v_VEHICLE_ID || '   DEPARTURE: ' || v_DEPARTURE || '   ARRIVAL: ' || v_ARRIVAL || '   DEPARTURE_DATE: ' || v_DEPARTURE_DATE || '   ARRIVAL_DATE: ' ||  v_ARRIVAL_DATE ;
    END IF;    
    
    RETURN v_ROUTE;
    
END;

BEGIN
DBMS_OUTPUT.PUT_LINE(routeOfContainer(447762, 200031));
END;