SET SERVEROUTPUT ON;
DROP TRIGGER NOT_EXCEED;

CREATE OR REPLACE TRIGGER NOT_EXCEED
BEFORE INSERT OR UPDATE
ON CONTAINER_CARGO_MANIFEST
FOR EACH ROW
DECLARE
--VAR_ID INTEGER;
VAR_NUMBER_CONTAINERS INTEGER;
VAR_CAPACITY_SHIP INTEGER;
EX_ERRO EXCEPTION;

BEGIN

/*SELECT ccm.CARGO_MANIFEST_ID
INTO VAR_ID
FROM CONTAINER_CARGO_MANIFEST ccm
INNER JOIN CARGO_MANIFEST cm ON cm.CARGO_MANIFEST_ID = ccm.CARGO_MANIFEST_ID
AND cm.CARGO_MANIFEST_ID = :NEW.CARGO_MANIFEST_ID;*/

SELECT COUNT(*) CONTAINER_ID
INTO VAR_NUMBER_CONTAINERS
FROM CONTAINER_CARGO_MANIFEST ccm
INNER JOIN CARGO_MANIFEST cm ON ccm.CARGO_MANIFEST_ID = cm.CARGO_MANIFEST_ID
INNER JOIN CONTAINER c ON c.CONTAINER_ID = ccm.CONTAINER_ID 
AND cm.CARGO_MANIFEST_ID = :NEW.CARGO_MANIFEST_ID;

SELECT CAPACITY
INTO VAR_CAPACITY_SHIP
FROM SHIP s
INNER JOIN SHIP_CONTAINER sc ON sc.MMSI = s.MMSI
INNER JOIN CONTAINER c ON c.CONTAINER_ID = sc.CONTAINER_ID
INNER JOIN CONTAINER_CARGO_MANIFEST ccm ON ccm.CONTAINER_ID = c.CONTAINER_ID
INNER JOIN CARGO_MANIFEST cm ON cm.CARGO_MANIFEST_ID = ccm.CARGO_MANIFEST_ID
AND cm.CARGO_MANIFEST_ID = :NEW.CARGO_MANIFEST_ID; 

IF
(VAR_CAPACITY_SHIP - VAR_NUMBER_CONTAINERS <= 0) 
THEN RAISE EX_ERRO;
END IF;

EXCEPTION
    WHEN EX_ERRO
    THEN
    RAISE_APPLICATION_ERROR(-20006, 'cargo manifest exceeded the ships capacity');
    
END NOT_EXCEED;

--Testing

INSERT INTO VEHICLE VALUES (25);
INSERT INTO TRIP VALUES(22,25,'LISBON', 'FARO', '2021-02-07', '2021-03-01');
INSERT INTO STOPS VALUES ('CASCAIS',22);
INSERT INTO SHIP VALUES (111111111, 'SEOUlEXPRE', 1111111, 21,'HELLO', 2, 12.3, 70, 294, 13, 25);
INSERT INTO CARGO_MANIFEST VALUES (23, 5, '2021-02-09', 'LEASING', 'CASCAIS', 25);
INSERT INTO CONTAINER VALUES (23, 124.2, 198.2, 876.4, 9, 1);
INSERT INTO SHIP_CONTAINER VALUES (23, 111111111);
INSERT INTO CONTAINER_CARGO_MANIFEST VALUES (23, 23, 1,2,3,123);

--Adiciona-se outro container ao mesmo cargo_manifest porque a capacidade de Ship é 2
INSERT INTO CONTAINER VALUES (24, 124.5, 198.1, 89.4, 9, 1);
INSERT INTO CONTAINER_CARGO_MANIFEST VALUES (23, 24, 2, 1, 2, 556);

--Erro porque já se está a tentar inserir um 3º container num SHIP com capacidade para 2 que já está cheio
INSERT INTO CONTAINER VALUES (25, 124.2, 198.2, 876.4, 9, 1);
INSERT INTO CONTAINER_CARGO_MANIFEST VALUES (23, 25, 1,3,4,890);


SELECT CONTAINER_ID
FROM CONTAINER
WHERE CONTAINER_ID = 23;

SELECT CARGO_MANIFEST_ID
FROM CARGO_MANIFEST
WHERE CARGO_MANIFEST_ID = 23;
